name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'demo/**'
    - 'themes/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Count
        run: |
          cd icons
          echo count=$(ls -l |grep "^d"|wc -l) >> $GITHUB_ENV
          cd ..

      - name: Get Date Env
        run: echo date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d') >> $GITHUB_ENV
      - name: Pack
        run: |
          chmod 755 ./.github/pack.sh
          ./.github/pack.sh

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'outputs/*'
          name: ${{steps.tag_version.outputs.new_tag}}
          tag_name: ${{steps.tag_version.outputs.new_tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: html
        run: |
          sed -i "s/{date}/${{ env.date }}/g" ./pages/index.md
          sed -i "s/{count}/${{ env.count }}/g" ./pages/index.md
          sed -i "s/{ver}/${{steps.tag_version.outputs.new_tag}}/g" ./pages/index.md
          sudo npm install -g markdown-styles
          generate-md --layout github --input ./pages --output ./outputs

      - name: build to netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ID }}
          build_directory: ./outputs
          NETLIFY_DEPLOY_TO_PROD: true

      - name: build to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-args: '--prod' #Optional
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./build