name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'readme.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Count
        run: |
          cd icons
          echo count=$(ls -l |grep "^d"|wc -l) >> $GITHUB_ENV
          cd ..
          echo date1=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d') >> $GITHUB_ENV
          echo date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M') >> $GITHUB_ENV
          echo tag=beta >> $GITHUB_ENV

      - name: Pack
        run: |
          chmod 755 ./.github/pack.sh
          ./.github/pack.sh
      - name: Upload Release Asset
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.tag }}
          prerelease: true
          title: ${{ env.date1 }}
          files: outputs/
      - name: upload
        run: |
          cd outputs
          path=$1
          files=$(ls $path)
          for filename in $files
          do
          curl -T AmethystLake_Rectangle.hwt -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/AmethystLake_Rectangle.hwt?version=latest"
          done