name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'readme.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Count
        run: |
          cd icons
          echo count=$(ls -l |grep "^d"|wc -l) >> config.ini
          cd ..
          echo date1=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d') >> $GITHUB_ENV
          echo date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M') >> config.ini
          echo tag=beta >> $GITHUB_ENV

      - name: html
        run: |
          sed -i "s/{date}/${{ env.date }}/g" ./pages/index.md
          sed -i "s/{count}/${{ env.count }}/g" ./pages/index.md
          sudo npm install -g markdown-styles
          generate-md --layout github --input ./pages --output ./outputpages

      - name: build to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-args: '--prod' #Optional
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./outputpages